import i18n from '@/i18n';

export default [
  {
    label: i18n.t('ExplorerLang.table.mtId'),
    displayValue: 'mtID',
    nativeValue: 'mtID',
    isNeedFormat: true,
    isFormatAddress: true,
    nftRouterParamsValue: 'denomId',
    isLink: true,
    isNft: true,
    linkRoute: '/mt/token?denom=',
    denomRouter: '&tokenId=',
  },
  {
    label: i18n.t('ExplorerLang.table.mtName'),
    displayValue: 'denomName',
    nativeValue: 'denomName',
    isNeedFormat: true,
    isFormatAddress: true,
  },
  {
    label: i18n.t('ExplorerLang.table.mtDenom'),
    displayValue: 'denomId',
    nativeValue: 'denomId',
    isNeedFormat: true,
    isFormatAddress: true,
  },
  {
    label: i18n.t('ExplorerLang.table.mtNumber'),
    displayValue: 'mtNumber',
    nativeValue: 'mtNumber',
  },
  {
    label: i18n.t('ExplorerLang.table.publisher'),
    displayValue: 'publisher',
    nativeValue: 'publisher',
    isLink: true,
    isNeedFormat: true,
    isFormatAddress: true,
    linkRoute: '/address/',
  },
  {
    label: i18n.t('ExplorerLang.table.ownerNumber'),
    displayValue: 'ownerCount',
    nativeValue: 'mtID',
    isLink: true,
    nftRouterParamsValue: 'denomId',
    isNft: true,
    linkRoute: '/mt/token?denom=',
    denomRouter: '&tokenId=',
  },
  {
    label: i18n.t('ExplorerLang.table.time'),
    displayValue: 'time',
    nativeValue: 'time',
    width: 160,
  },
];
